name: Parent Workflow

on:
  workflow_dispatch:
    inputs:
      service_tier:
        description: 'Service tier'
        required: true
        type: choice
        options:
          - 'engineering'
          - 'nonproduction'
          - 'production'
        default: 'engineering'

permissions:
  contents: write

jobs:
  call_child_workflow:
    uses: ./.github/workflows/parse-yaml
    with:
      service_tier: ${{ github.event.inputs.service_tier }}
