name: Parse YAML

on:
  # Allows the workflow can be triggered by
  # an upstream workflow.
  workflow_call:
    inputs:
      service_tier:
        type: string
        required: true
  # Allows the workflow to be triggered manually.
  workflow_dispatch:
    inputs:
      service_tier:
        description: 'Service tier'
        required: true
        type: choice
        options:
          - 'engineering'
          - 'nonproduction'
          - 'production'
        default: 'engineering'

permissions:
  contents: write

env:
  service_tier: ${{ github.event.inputs.service_tier || inputs.service_tier }}

jobs:
  parse_yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse YAML
        # Convert the YAML file to minified JSON.
        id: parse-yaml
        shell: bash
        run: |
          parsed_json="$(yq -I0 -o=json eval '.config' './config/${{ env.service_tier }}.yaml')"
          echo "parsed_json=${parsed_json}" >> "$GITHUB_OUTPUT"

      - name: Print outputs
        id: print-outputs
        env:
          DATABASE_HOST: ${{ fromJson(steps.parse-yaml.outputs.parsed_json).database.host }}
        run: |
          which yq || echo "yq is not installed"
          echo "Database host: ${DATABASE_HOST}"
