name: Parse YAML

on:
  push:

permissions:
  contents: write

jobs:
  parse_yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse YAML
        id: parse-yaml
        uses: mikefarah/yq@v4
        with:
          cmd: yq -o=json eval '.config' './config/sample.yaml'

      - name: Generate individual outputs
        id: generate-outputs
        env:
          PARSED_JSON: ${{ steps.parse-yaml.outputs.result }}
        run: |
          echo $PARSED_JSON | jq -r '.database.host'
          echo "database_host=$(echo $PARSED_JSON | jq -r '.database.host')" >> "$GITHUB_ENV"
          echo $PARSED_JSON | jq -r '.database.port'
          echo "database_port=$(echo $PARSED_JSON | jq -r '.database.port')" >> "$GITHUB_ENV"

      - name: Print outputs
        id: print-outputs
        env:
          DATABASE_HOST: ${{ steps.generate-outputs.outputs.database_host }}
          DATABASE_PORT: ${{ steps.generate-outputs.outputs.database_port }}
        run: |
          echo "Database host: ${DATABASE_HOST}"
          echo "Database port: ${DATABASE_PORT}"
