name: Parse YAML

on:
  push:

permissions:
  contents: write

jobs:
  parse_yaml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse YAML
        id: parse-yaml
        uses: mikefarah/yq@v4
        with:
          cmd: yq -o=json eval '.config' './config/sample.yaml'

      - name: Use parsed YAML data
        env:
          PARSED_JSON: ${{ steps.parse-yaml.outputs.result }}
        run: |
          echo "Parsed result (as a JSON string) is: '${PARSED_JSON}'"
